resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
- files:
  - Dockerfile=sonataflow_builder_dockerfile.yaml
  literals:
  - DEFAULT_BUILDER_RESOURCE_NAME=Dockerfile
  - DEFAULT_WORKFLOW_EXTENSION=.sw.json
  name: builder-config

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:8d76f495d7095faf64086725f79df0c8d7edb575e30306ada15057a58bdfead7
  name: controller
  newName: registry.redhat.io/openshift-serverless-1-tech-preview/logic-rhel8-operator
# Patching the manager deployment file to add an env var with the operator namespace in
patchesJson6902:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    namespace: system
    version: v1
